/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./components/StarWars.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    EditablePersonInfo: typeof import('./components/EditablePersonInfo.vue')['default']
    EditablePesonInfo: typeof import('./components/EditablePersonInfo.vue')['default']
    HelloWorld: typeof import('./components/StarWars.vue')['default']
    HelloWorld2: typeof import('./components/PeopleList.vue')['default']
    PeopleCard: typeof import('./components/PeopleCard.vue')['default']
    PeopleList: typeof import('./components/PeopleList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
